version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - apt-get update -y
      - sudo apt-get install php-mysql
      - sudo service apache2 restart
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - apt-get install -y libpq-dev libzip-dev
      - apt-get install -y php-pgsql
      - curl -sS https://getcomposer.org/installer -o composer-setup.php 
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  pre_build:
    commands:
      - composer update
      - npm install
      - cp .env.example .env
      - php artisan key:generate
      - php artisan config:cache
      - ls -al
      - php -m | grep PDO
      - php artisan migrate
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
  upload-artifacts: yes
  logs: yes